name: Conventional Commits CI

permissions:
  pull-requests: write
  contents: read


on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ main ]

jobs:
  conventional-commits:
    name: Check Conventional Commits Conformity
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Lint PR title and commits for Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build
        run: make build
      - name: Run tests
        run: make test

  release:
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install semantic-release and plugins
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/exec
      - name: Get next version
        id: next_version
        run: |
          VERSION=$(npx semantic-release --dry-run | grep 'next release version is' | awk '{print $NF}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Build Linux binary
        run: make build-linux
        env:
          VERSION: ${{ steps.next_version.outputs.version }}
      - name: Build macOS Intel binary
        run: make build-macos-intel
        env:
          VERSION: ${{ steps.next_version.outputs.version }}
      - name: Build macOS ARM64 binary
        run: make build-macos-arm64
        env:
          VERSION: ${{ steps.next_version.outputs.version }}
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: semantic-release --debug
